export const LOGIN = 'user/login';

export const USER_DETAIL = 'user/getdetails';
export const FETCH_EXPENSES = 'expenses/get-expenses';
export const ADD_EXPENSE='expenses/register';
export const EDIT_EXPENSE='/expenses/get-expenses-detail/';
export const UPDATE_EXPENSE='/expenses/update-expenses/';
export const DELETE_EXPENSE='expenses/removeExpenses/';
export const FETCH_COMPANIES = 'customers/get-customers';
export const ADD_CUSTOMER = 'customers/register';
export const FETCH_PACKAGES = '/packages/get-packages';
export const ADD_PACKAGES='/packages/register';
export const EDIT_PACKAGES='/packages/get-package-detail/';
export const UPDATE_PACKAGES='/packages/update-package/';
export const DELETE_PACKAGES='/packages/removePackages/';
export const EDIT_CUSTOMER = '/customers/get-customer-details/';
export const UPDATE_CUSTOMER = '/customers/update-customer/';
export const UPDATE_PAYMENT = '/customers/update-payment/';
export const DEL_CUSTOMER = '/customers/removeCustomers/';
